name: ScholarshipSportsUSA
favicon: null
layout_spectrum: 0.9402993835974485
typography_spectrum: 0.09045661613345146
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.12998295878060162
  lightness: 0.04680694662965834
  saturation: 0.18900430132634938
  rhythmicContrast: 0.5252858852036297
purpose: []
